workflows:
  build-android-apk:
    name: Build Android APK (Expo)
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas build -p android --profile preview --non-interactive
    artifacts:
      - ./dist/*.apk
